FROM node:20-alpine AS builder

WORKDIR /app
COPY frontend/package*.json .
RUN npm ci
COPY frontend/ .
RUN npm run build
RUN npm prune --production

FROM node:20-alpine

WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY frontend/package.json .
COPY frontend/.env .
ENV NODE_ENV=production

EXPOSE 3000

WORKDIR /app
CMD ["node", "--env-file=.env", "build"]
